/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-microblaze"
#define TARGET_ARCH "microblaze"
#define TARGET_MICROBLAZE 1
#define TARGET_PHYS_ADDR_BITS 64
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_SOFTMMU 1
#define CONFIG_SOFTFLOAT 1
#define CONFIG_I386_DIS 1
#define CONFIG_MICROBLAZE_DIS 1
#define CONFIG_NEED_MMU 1
