/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-sh4"
#define TARGET_ARCH "sh4"
#define TARGET_SH4 1
#define TARGET_PHYS_ADDR_BITS 64
#define CONFIG_USER_ONLY 1
#define CONFIG_LINUX_USER 1
#define CONFIG_NOSOFTFLOAT 1
#define TARGET_HAS_BFLT 1
#define CONFIG_USE_NPTL 1
#define CONFIG_USE_GUEST_BASE 1
#define CONFIG_I386_DIS 1
#define CONFIG_SH4_DIS 1
