# Automatically generated by configure - do not modify
CONFIG_QEMU_PREFIX="/usr/gnemul/qemu-cris"
TARGET_ARCH=cris
TARGET_CRIS=y
TARGET_ARCH2=cris
TARGET_BASE_ARCH=cris
TARGET_ABI_DIR=cris
TARGET_PHYS_ADDR_BITS=64
CONFIG_SOFTMMU=y
LIBS+=-lutil -lncurses  -ljpeg -L/usr/lib/x86_64-linux-gnu -lSDL -lX11 
HWLIB=../libhw64/libqemuhw64.a
CONFIG_NOSOFTFLOAT=y
CONFIG_I386_DIS=y
CONFIG_CRIS_DIS=y
CONFIG_NEED_MMU=y
LDFLAGS+=
QEMU_CFLAGS+=-I$(SRC_PATH)/fpu -I$(SRC_PATH)/tcg -I$(SRC_PATH)/tcg/$(ARCH) 
