/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-ppc64"
#define TARGET_ARCH "ppc64"
#define TARGET_PPC64 1
#define TARGET_PPC 1
#define TARGET_PHYS_ADDR_BITS 64
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_USER_ONLY 1
#define CONFIG_LINUX_USER 1
#define CONFIG_SOFTFLOAT 1
#define CONFIG_USE_GUEST_BASE 1
#define CONFIG_I386_DIS 1
#define CONFIG_PPC_DIS 1
