/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-mipsel"
#define TARGET_ABI_MIPSO32 1
#define TARGET_ARCH "mips"
#define TARGET_MIPS 1
#define TARGET_PHYS_ADDR_BITS 64
#define CONFIG_USER_ONLY 1
#define CONFIG_LINUX_USER 1
#define CONFIG_SOFTFLOAT 1
#define CONFIG_USE_NPTL 1
#define CONFIG_USE_GUEST_BASE 1
#define CONFIG_I386_DIS 1
#define CONFIG_MIPS_DIS 1
