/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-sh4"
#define TARGET_ARCH "sh4"
#define TARGET_SH4 1
#define TARGET_PHYS_ADDR_BITS 64
#define CONFIG_SOFTMMU 1
#define CONFIG_NOSOFTFLOAT 1
#define CONFIG_I386_DIS 1
#define CONFIG_SH4_DIS 1
