/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-m68k"
#define TARGET_ARCH "m68k"
#define TARGET_M68K 1
#define TARGET_PHYS_ADDR_BITS 64
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_SOFTMMU 1
#define CONFIG_SOFTFLOAT 1
#define CONFIG_I386_DIS 1
#define CONFIG_M68K_DIS 1
