# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu-s5pc110/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu-s5pc110/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu-s5pc110/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu-s5pc110/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu-s5pc110/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu-s5pc110/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu-s5pc110/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu-s5pc110/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vonnyfly/android_src/qemu/qemu-s5pc110/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
