/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-cris"
#define TARGET_ARCH "cris"
#define TARGET_CRIS 1
#define TARGET_PHYS_ADDR_BITS 64
#define CONFIG_USER_ONLY 1
#define CONFIG_LINUX_USER 1
#define CONFIG_NOSOFTFLOAT 1
#define CONFIG_USE_NPTL 1
#define CONFIG_USE_GUEST_BASE 1
#define CONFIG_I386_DIS 1
#define CONFIG_CRIS_DIS 1
