/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-alpha"
#define TARGET_ARCH "alpha"
#define TARGET_ALPHA 1
#define TARGET_PHYS_ADDR_BITS 64
#define CONFIG_USER_ONLY 1
#define CONFIG_LINUX_USER 1
#define CONFIG_NOSOFTFLOAT 1
#define CONFIG_USE_GUEST_BASE 1
#define CONFIG_I386_DIS 1
#define CONFIG_ALPHA_DIS 1
