/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-mips64el"
#define TARGET_ABI_MIPSN64 1
#define TARGET_ARCH "mips64"
#define TARGET_MIPS64 1
#define TARGET_MIPS 1
#define TARGET_PHYS_ADDR_BITS 64
#define CONFIG_SOFTMMU 1
#define CONFIG_SOFTFLOAT 1
#define CONFIG_I386_DIS 1
#define CONFIG_MIPS_DIS 1
